### ISSUE TITLE
[doubt] Astrodon deno ts rust relation ?

### ISSUE THREAD

**Issue by elycheikhsmail** [astrodon/astrodon#12]
I hope to see more explanation for relation between ( deno, ts ) and ( Astrodon/tauri , rust )
for Astrodon consumer and Astrodon developer.
for example is rust for Astrodon consumer in certain situation ? what skils needed for me or any dev to be able to contribue to Astrodon ?

**Comment by marc2332** [comment]
Hello,

Astrodon contains a deno module that uses a [shared library](https://github.com/astrodon/astrodon/tree/main/modules/astrodon-tauri) made in rust through FFI, this acts as a bridge between Deno and Tauri. 

Astrodon also contains a [builder](https://github.com/astrodon/astrodon/tree/main/modules/astrodon-build) to compile your app correctly (`deno compile` is not enough). 

And it also contains a WIP cli (useless for now).

Anyway, your app is still running in Deno, so you can write the code you want, as you would do in any other Deno app.

Does that answer your question?

**Comment by elycheikhsmail** [comment]
> Hello,
> 
> Astrodon contains a deno module that uses a [shared library](https://github.com/astrodon/astrodon/tree/main/modules/astrodon-tauri) made in rust, through FFI, this acts as a bridge between Deno and Tauri.
> 
> Astrodon also contains a [builder](https://github.com/astrodon/astrodon/tree/main/modules/astrodon-build) to compile your app correctly (`deno compile` is not enough).
> 
> And it also contains a WIP cli (useless for now).
> 
> Anyway, your app is still running in Deno, so you can write the code you want, as you would do in any other Deno app.
> 
> Does that answer your question?

thank you for now it is suffisant. I hope add this explantion to read me.

**Comment by elycheikhsmail** [comment]
all deno api is accessible with Astrodon ? like deno.write ?

**Comment by elycheikhsmail** [comment]
can you give me more details  about WIP cli ?

**Comment by marc2332** [comment]
> all deno api is accessible with Astrodon ? like deno.write ?

You can only use Deno in the backend. But, it is possible to create global functions on the shared library side, and call them from the webview process. That's something we want to add once the callbacks can be passed to through FFI.

**Comment by marc2332** [comment]
> can you give me more details about WIP cli ?

There is nothing to see now, but we want to it be able to create projects (like templates) or to easily create an executable, etc. We still to need to plan it.

**Comment by denyncrawford** [comment]
@elycheikhsmail No, at this moment Astrodon is in alpha phase, which means that only the core is being built. With astrodon you can (by now):

- Open a window with a url (locally and remote) or with the asset packager, some how like in [this example](https://github.com/astrodon/astrodon/blob/main/examples/vuejs_app/mod.ts)
- Comunicate from deno to render process (but not: render to deno, WIP)
- Make some configurations with our config file standard (wip)
- Build self contained apps with our builder package.

So, where you can use Denos API's? In backend only at the moment.

Also we don't have plans to make an integration of deno core apis or x modules support in render process at least in a while.

If you have any other doubts with astrodon, please use the official communication channel on our [discord server](https://discord.gg/ybBpdGYv). Issues will be opened for bugs, contributions and reports only, thank you so much for your interest in astrodon!

**Comment by elycheikhsmail** [comment]
thank you @denyncrawford  and @marc2332
