### ISSUE TITLE
https://astrodon.land/ home page demo failed

### ISSUE THREAD

**Issue by elycheikhsmail** [astrodon/astrodon#42]
I create gui.ts file and copy past

```

import { AppWindow  } from "https://deno.land/x/astrodon/mod.ts";

const win = new AppWindow("Window A");

win.setHtml("<h1>Hello World :)</h1>");

await win.run();

```

from https://astrodon.land/ web site
I get the following error :

```
ely@ely-ThinkPad-T450s:~/Documents/fullstack/astrodon-explore$ deno run -A --unstable gui.ts
Check file:///home/ely/Documents/fullstack/astrodon-explore/gui.ts
error: TS2305 [ERROR]: Module '"https://deno.land/x/astrodon@0.1.0-alpha.2/mod.ts"' has no exported member 'AppWindow'.
import { AppWindow  } from "https://deno.land/x/astrodon/mod.ts";
         ~~~~~~~~~
    at file:///home/ely/Documents/fullstack/astrodon-explore/gui.ts:1:10

```

**Comment by marc2332** [comment]
because https://astrodon.land/ is WIP.

Follow this example: https://deno.land/x/astrodon@0.1.0-alpha.2/examples/hello_world/demo.ts

**Comment by elycheikhsmail** [comment]
I made this change

```
import { App  } from "https://deno.land/x/astrodon/mod.ts";

export const getIndex = async () => {
  const isDev = Deno.env.get("DEV") == "true";
 
  //deno-lint-ignore no-explicit-any
  const isProd = (globalThis as any).astrodonProduction

  if (isDev || isProd) {
    return `file://${ await Deno.realPath('./renderer/index.html')}`;
  } else {
    return `https://raw.githack.com/astrodon/astrodon/dev/examples/hello_world/renderer/index.html` //"<your_remote_html>";
  }
};

const indexPath = await getIndex();

const app = await App.new();

await app.registerWindow({ title: "spaghettis > ravioli", url: indexPath });

setInterval(() => {
  app.send(`Hello Tauri: ${Math.random()}`);
}, 500);

app.run();
```
and it work as standalone script
thank you
why not fix this in asrodon.land ?

**Comment by marc2332** [comment]
> I made this change
> 
> ```
> import { App  } from "https://deno.land/x/astrodon/mod.ts";
> 
> export const getIndex = async () => {
>   const isDev = Deno.env.get("DEV") == "true";
>  
>   //deno-lint-ignore no-explicit-any
>   const isProd = (globalThis as any).astrodonProduction
> 
>   if (isDev || isProd) {
>     return `file://${ await Deno.realPath('./renderer/index.html')}`;
>   } else {
>     return `https://raw.githack.com/astrodon/astrodon/dev/examples/hello_world/renderer/index.html` //"<your_remote_html>";
>   }
> };
> 
> const indexPath = await getIndex();
> 
> const app = await App.new();
> 
> await app.registerWindow({ title: "spaghettis > ravioli", url: indexPath });
> 
> setInterval(() => {
>   app.send(`Hello Tauri: ${Math.random()}`);
> }, 500);
> 
> app.run();
> ```
> and it work as standalone script
> thank you
> why not fix this in asrodon.land ?

Because the website isnt supposed to be seen yet.
