### ISSUE TITLE
Don't let this die 🥹 🦖 💀

### ISSUE THREAD

**Issue by SrGeneroso** [astrodon/astrodon#54]
I've been talking a lot in the discord server about deno desktop apps, tauri and deno would be a killer feature for both. I know is hard since both deno and tauri are in their early stages, but would be trully awesome.
Any side-projects related to this?

**Comment by katungi** [comment]
I haven't seen any so far. But I would be interested to keep this going. It's such an interesting project.

**Comment by SrGeneroso** [comment]
cleaning issues, hope we find oil from this dino in the future😘
